### ISSUE TITLE
Formatting numbers, dates, etc

### ISSUE THREAD

**Issue by jswiss** [mikemenaker/vue-data-table#1]
Hey Mike, great work on this. Maybe it's because it's the end of the day and my brain is now mush, but I can't figure out how to format numbers and dates using your table. With a regular HTML table with Vue directives and interpolation, I can just pass a filter within the double curly braces. Know how I could go about doing that with your tool?

**Comment by mikemenaker** [comment]
You can pass in a slot to be used for a column instead of just the value, if you wanted a column "name" to always be bold:

``` html
<div id="demo">  
  <data-table :data="gridData">    
    <template slot="name" scope="props">
      <b>{{props.entry.name}}</b>
    </template>
  </data-table>
</div>
```

**Comment by jswiss** [comment]
Awesome, thanks!
